version: '3.3'
services:
  server:
    image: grpc-http-rest-project/info-service:latest
    container_name: info-service
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - GRPC_PORT=9090
      - HTTP_PORT=8080
    networks:
      grpc:
        aliases:
          - backend.local
networks:
  grpc:
